apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeclock-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: timeclock-api
  template:
    metadata:
      labels:
        app: timeclock-api
    spec:
      containers:
        - name: timeclock-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}